apiVersion: apps/v1
kind: Deployment
metadata:
  name: airsonic
  labels:
    app: airsonic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: airsonic
  template:
    metadata:
      labels:
        app: airsonic
    spec:
      containers:
      - name: airsonic
        image: ${{ secrets.ACR_LOGIN_SERVER }}/airsonic:${{ github.sha }}
        ports:
        - containerPort: 4040
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: airsonic-data
          mountPath: /var/airsonic
      volumes:
      - name: airsonic-data
        persistentVolumeClaim:
          claimName: airsonic-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: airsonic
spec:
  selector:
    app: airsonic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4040
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airsonic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
